[theme]
primaryColor = "pink"
backgroundColor = "#e07a5f"
secondaryBackgroundColor = "Snow"
codeBackgroundColor = "green"
textColor = "SteelBlue"
linkColor = "#764ba2"
baseRadius = "10px"
showWidgetBorder = false
font = "monospace"
baseFontSize=15
[theme.sidebar]
primaryColor = "MediumTurquoise"
backgroundColor = "#81b29a"
textColor = "#f4f1de"
baseRadius = "7px"
font = "sans-serif"